import { MediaItem } from './types';

export const mediaLibrary: MediaItem[] = [
  {
    id: 'bbb-1',
    title: 'Big Buck Bunny',
    poster: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/400px-Big_buck_bunny_poster_big.jpg',
    thumbnail: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Big_buck_bunny_poster_big.jpg/800px-Big_buck_bunny_poster_big.jpg',
    duration: 596,
    year: 2008,
    genre: 'Animation',
    description: 'A large and lovable rabbit deals with three tiny bullying rodents — a riff on the classic bully-picks-on-gentle-giant story.',
    audio: [
      { id: 0, label: 'English 5.1', lang: 'en' },
      { id: 1, label: 'Русский', lang: 'ru' },
    ],
    subtitles: [
      { id: 'off', label: 'Off', lang: 'off' },
      { id: 'en', label: 'English', lang: 'en' },
      { id: 'ru', label: 'Русский', lang: 'ru' },
    ],
    qualities: ['Auto', '480p', '720p', '1080p'],
    status: 'ready',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  },
  {
    id: 'ed-2',
    title: 'Elephants Dream',
    poster: 'https://picsum.photos/seed/elephantsdream/400/600',
    thumbnail: 'https://picsum.photos/seed/elephantsdream/800/450',
    duration: 654,
    year: 2006,
    genre: 'Sci-Fi Animation',
    description: 'Two strange characters explore a vast mechanical world. The first Blender open movie project.',
    audio: [
      { id: 0, label: 'English', lang: 'en' },
      { id: 1, label: 'Français', lang: 'fr' },
    ],
    subtitles: [
      { id: 'off', label: 'Off', lang: 'off' },
      { id: 'en', label: 'English', lang: 'en' },
    ],
    qualities: ['Auto', '720p', '1080p'],
    status: 'ready',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  },
  {
    id: 'tos-3',
    title: 'Tears of Steel',
    poster: 'https://picsum.photos/seed/tearsofsteel/400/600',
    thumbnail: 'https://picsum.photos/seed/tearsofsteel/800/450',
    duration: 734,
    year: 2012,
    genre: 'Sci-Fi',
    description: 'In a dystopian future, a group of soldiers and scientists takes refuge in Amsterdam. A Blender Institute short film.',
    audio: [
      { id: 0, label: 'English 5.1', lang: 'en' },
      { id: 1, label: 'Русский', lang: 'ru' },
    ],
    subtitles: [
      { id: 'off', label: 'Off', lang: 'off' },
      { id: 'en', label: 'English', lang: 'en' },
      { id: 'ru', label: 'Русский', lang: 'ru' },
    ],
    qualities: ['Auto', '480p', '720p', '1080p'],
    status: 'ready',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  },
  {
    id: 'sow-4',
    title: 'Sintel',
    poster: 'https://picsum.photos/seed/sintel2024/400/600',
    thumbnail: 'https://picsum.photos/seed/sintel2024/800/450',
    duration: 888,
    year: 2010,
    genre: 'Fantasy',
    description: 'A lonely young woman, Sintel, helps and befriends a dragon, whom she calls Scales. A Blender Foundation film.',
    audio: [
      { id: 0, label: 'English', lang: 'en' },
      { id: 1, label: 'Español', lang: 'es' },
      { id: 2, label: 'Русский', lang: 'ru' },
    ],
    subtitles: [
      { id: 'off', label: 'Off', lang: 'off' },
      { id: 'en', label: 'English', lang: 'en' },
      { id: 'ru', label: 'Русский', lang: 'ru' },
      { id: 'es', label: 'Español', lang: 'es' },
    ],
    qualities: ['Auto', '480p', '720p', '1080p'],
    status: 'ready',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
  },
  {
    id: 'cf-5',
    title: 'Cosmos Laundromat',
    poster: 'https://picsum.photos/seed/cosmos2024/400/600',
    thumbnail: 'https://picsum.photos/seed/cosmos2024/800/450',
    duration: 1260,
    year: 2015,
    genre: 'Drama',
    description: 'On a desolate island, a suicidal man named Franck meets a mysterious salesman who offers him the ultimate deal.',
    audio: [
      { id: 0, label: 'English 5.1', lang: 'en' },
    ],
    subtitles: [
      { id: 'off', label: 'Off', lang: 'off' },
      { id: 'en', label: 'English', lang: 'en' },
    ],
    qualities: ['Auto', '1080p'],
    status: 'ready',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  },
  {
    id: 'proc-6',
    title: 'Untitled Project 2024',
    poster: 'https://picsum.photos/seed/untitled2024/400/600',
    thumbnail: 'https://picsum.photos/seed/untitled2024/800/450',
    duration: 7200,
    year: 2024,
    genre: 'Unknown',
    description: 'Processing...',
    audio: [{ id: 0, label: 'Русский', lang: 'ru' }],
    subtitles: [{ id: 'off', label: 'Off', lang: 'off' }],
    qualities: ['Auto'],
    status: 'processing',
    videoUrl: '',
  },
];
